name: Run Tests on Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'graalvm'
          java-version: '21'
          cache: 'gradle'
          cache-dependency-path: | # optional
            ~/*.gradle*
            ~/**/gradle-wrapper.properties

      - name: Grant Execute Permission to Gradlew
        run: chmod +x gradlew

      - name: Run Tests
        run: ./gradlew test